codes/bookstore/books/urls.py
# books/urls.py

from django.conf.urls import url

from .views import (    http_example,
        fexample, CExample,
        book_list, BookList, AuthorList,
        BookDetail,
        read_arg, read_kwarg, ReadArg, ReadKwarg,
        SearchBooks, QSearchBooks, BookSearch, BookSearchResult, 
        author_create, AuthorCreate, BookUpdate,
    )

# f in the link name, is used for function based view, otherwise class based view

urlpatterns = [
    url(r'^httpExample/$', http_example, name="httpExample"), # HttpResponse
    url(r'^fexample/$', fexample, name="fexample"), # function-based-view
    url(r'^cexample/$', CExample.as_view(), name="cexample"), # class-based-view

    
    url(r'^fbooklist/$', book_list, name="fbooklist"), # Book list
    url(r'^$', BookList.as_view(), name="booklist"), # Book list
    url(r'^authorlist/$', AuthorList.as_view(), name="authorlist"), # Author list


    url(r'^(?P<pk>\d+)/$', BookDetail.as_view(), name="bookdetail"), # Book list


    url(r'^freadargs/(\w+)/$', read_arg, name="freadargs"), # Read from url
    url(r'^readargs/(\w+)/$', ReadArg.as_view(), 
                                    name="readargs"), # Read from url
    url(r'^freadkwargs/(?P<test>\w+)/$', read_kwarg, 
                                    name="freadkwargs"), # Read from url
    url(r'^readkwargs/(?P<test>\w+)/$', ReadKwarg.as_view(), 
                                    name="readkwargs"), # Read from url


    url(r'^searchfromurl/(?P<urlsearch>[\w-]+)/$', SearchBooks.as_view(),
                name="searchfromurl"), # search item received from url
    url(r'^qsearchfromurl/(?P<qurlsearch>[\w-]+)/$', QSearchBooks.as_view(),
                name="qsearchfromurl"), # search item received from url using Q


    url(r'^booksearch/$', BookSearch.as_view(), 
                            name="booksearch"), #Book search
    url(r'^booksearchresult/$', BookSearchResult.as_view(), 
                                name="booksearchresult"), # Book search


    url(r'^fauthorcreate/$', author_create, 
                                    name="fauthorcreate"), # create author
    url(r'^authorcreate/$', AuthorCreate.as_view(), 
                                    name="authorcreate"), # create author

    url(r'^(?P<pk>\d+)/update/$', BookUpdate.as_view(), 
                                    name="bookupdate"), # update book
]

codes/bookstore/bookstore/urls.py
# Configuration-folder/urls.py

from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView

from .views import all_links 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', all_links, name="home"),  # home page

    url(r'^books/', include("books.urls", namespace="book")), # books app

    # default location for html is 'registration/login.html'
    # url(r'^login/', LoginView.as_view(), name='login' ), 
    # url(r'^logout/', LogoutView.as_view(), name='logout' ), 

    url(r'^accounts/', include('registration.backends.default.urls')),
]


# required to see the media files in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codes/bookstore/bookstore/views.py
# bookstore/views.py

from django.shortcuts import render

# look template in 'root folder'
# The folder 'templates' is not checked inside the 'configuration folder'
# But it is checked inside the 'app' folder
def all_links(request):
    return render(request, 'bookstore/link_page.html')

codes/bookstore/templates/bookstore/link_page.html
<!-- templates/bookstore/all_links.html -->

{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

    <h1> Links </h1>

    <table class="table">
        <tr>
            <th> View name ( with URL) </th>
            <th> Type </th>
            <th> Description</th>
        </tr>
        <tr>
            <td> <a href="{% url 'home' %}">bookstore/views/all_links</a></td>
            <td> Home page of this website </td>
            <td>List of links</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:httpExample' %}">books/views/http_example</a></td>
            <td> function based view </td>
            <td>HttpResponse</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:fexample' %}">books/views/fexample</a></td>
            <td> function based view </td>
            <td>Context in "function based" view</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:cexample' %}">books/views/cexample</a></td>
            <td> TemplateView </td>
            <td>Context in "Class based" view</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:fbooklist' %}">books/views/book_list</a></td>
            <td> function based view </td>
            <td>Book list</td>
        </tr>
        <tr>
            <!-- <td> <a href="{% url 'book:booklist' %}">books/views/BookList</a></td> -->
            <td> <a href="{{book.book.get_book_list_url}}">books/views/BookList</a></td>
            <td> ListView </td>
            <td>Book list : <b>book.book.get_book_list_url</b> is used in url <br>
                i.e. <b>go to folder-book->class-book->get_book_list_url</b> </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:authorlist' %}">books/views/AuthorList</a></td>
            <td> function based view </td>
            <td>Author list</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:booklist' %}">books/views/BookDetail</a></td>
            <td> DetailView </td>
            <td>Go to list page and click on any book for details<br>
                <b>(ManyToMany and ForeignKey)</b>
            </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:freadargs' 'tiger' %}">books/views/read_arg</a></td>
            <td> function based view </td>
            <td> Read args from URL </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:readargs' 'tiger' %}">books/views/ReadArgs</a></td>
            <td> TemplateView </td>
            <td> Read args from URL <br> 
                <b>url 'book:readargs' 'tiger'</b>
            </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:freadkwargs' test='tiger' %}">books/views/read_kwarg</a></td>
            <td>  function based view  </td>
            <td> Read kwargs from URL <br>
                 <b>url 'book:freadkwargs' test='tiger'</b> 
            </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:readkwargs' test='tiger' %}">books/views/ReadKwarg</a></td>
            <td> TemplateView </td>
            <td> Read kwargs from URL </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:searchfromurl' urlsearch='ing'%}">books/views/SearchBooks</a></td>
            <td> ListView </td>
            <td> Search book by reading URL </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:qsearchfromurl' qurlsearch='ah'%}">books/views/QSearchBooks</a></td>
            <td> ListView </td>
            <td> Q Search book by reading URL <br>
                <b>(ManyToMany and ForeignKey)</b>
            </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:booksearch' %}">books/views/BookSearch</a></td>
            <td> TemplateView </td>
            <td> Go to search page </td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:booksearchresult' %}?q=ch">books/views/BookSearchResult</a></td>
            <td> ListView </td>
            <td> Fill search value and press enter</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:fauthorcreate' %}">books/views/author_create</a></td>
            <td> function based view </td>
            <td> Form to create Author (only staff can create)</td>
        </tr>
        <tr>
            <td> <a href="{% url 'book:authorcreate' %}">books/views/AuthorCreate</a></td>
            <td> CreateView </td>
            <td> Form to create Author (only staff can create)</td>
        </tr>
        <tr>
            <td> <a href="books/1/update/">books/views/BookUpdate</a></td>
            <td> UpdateView </td>
            <td> Form to update books <br>
                (Login as "staff") or </br>
                (change 1 to correct 'id' in book/1/update/)
            </td>
        </tr>
    </table>

{% endblock %}